# DigitalOcean App Platform Configuration
name: ai-assistant-v2
services:
- name: telegram-bot
  source_dir: /
  github:
    repo: IrinaShafeeva/telegram-ai-assistant
    branch: main
  run_command: node stable-app.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  - path: /webhook
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: TELEGRAM_BOT_TOKEN
    value: 8450163657:AAG0c4YmaZga83Iye6ymxWt5syMfgjMvYvs
    type: SECRET
  - key: OPENAI_API_KEY  
    value: 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
    type: SECRET
  - key: SUPABASE_URL
    value: https://hbswrnjykwyedltjroxw.supabase.co
    type: SECRET
  - key: SUPABASE_ANON_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhic3dybmp5a3d5ZWRsdGpyb3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjM2MDYsImV4cCI6MjA2OTY5OTYwNn0.i1XaVH_HZ81Zy8jOMMf5T20V10U8M5aApqdUH8oH1Oo
    type: SECRET
  - key: SUPABASE_SERVICE_ROLE_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhic3dybmp5a3d5ZWRsdGpyb3h3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDEyMzYwNiwiZXhwIjoyMDY5Njk5NjA2fQ.45jCraPFG0MA9v8VFEzXNAAN0jHjKR7AAebIYXD9Izk
    type: SECRET